<?php
// $Id$

/**
 * @file
 * Display a Google Custom Search Engine on your site.
 */

/**
 * Implementation of hook_menu().
 */
function google_cse_menu() {
  if (variable_get('google_cse_results_display', 'here') != 'google') {
    $items['search/google'] = array(
      'access arguments' => array('search Google CSE'),
      'title' => 'Google',
      'description' => 'Google Co-op Custom Search Engine',
      'page callback' => 'google_cse_results', 
      'type' => MENU_LOCAL_TASK,
    );
  }
  $items['admin/settings/google_cse'] = array(
    'access arguments' => array('administer site configuration'),
    'title' => 'Google CSE',
    'description' => 'Configure the Google Co-op Custom Search Engine.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_cse_admin_settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'google_cse.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function google_cse_theme() {
  return array('google_cse_results' => array('file' => 'google_cse.theme.inc'));
}

/**
 * Implementation of hook_block().
 */
function google_cse_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks = array();
    $blocks[] = array('info' => t('Google Co-op CSE'));
    return $blocks;
  }
  else if ($op == 'view' && user_access('search Google CSE')) {
    return array('subject' => t('Search'), 'content' => drupal_get_form('google_cse_searchbox_form'));
  } 
}

/**
 * Implementation of hook_forms();
 */
function google_cse_forms() { 
  $forms = array();
  $forms['google_cse_searchbox_form'] = array( 
    'callback' => 'google_cse_searchbox_form_builder', 
    'callback arguments' => array('google_cse_searchbox_form'),
  ); 
  $forms['google_cse_results_searchbox_form'] = array( 
    'callback' => 'google_cse_searchbox_form_builder', 
    'callback arguments' => array('google_cse_results_searchbox_form'),
  ); 
  return $forms; 
}

/**
 * Form builder for the searchbox forms.
 */
function google_cse_searchbox_form_builder(&$form_state, $form_id) {
  $form = array();
  // The default form.
  if (variable_get('google_cse_results_display', 'here') == 'here') {
    $form['#action'] = url('search/google');
    $cof = 'FORID:11';
  }
  else {
    $form['#action'] = 'http://'. variable_get('google_cse_domain', 'www.google.com') .'/cse';
    $cof = 'FORID:0';
  }
  $form['#method'] = 'get';
  $form['cx'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('google_cse_cx', ''),
  );
  $form['cof'] = array(
    '#type' => 'hidden',
    '#value' => $cof,
  );
  $form['query'] = array(
    '#type' => 'textfield',
    '#default_value' => isset($_GET['query']) ? $_GET['query'] : '',
  );
  $form['sa'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  drupal_add_js(drupal_get_path('module', 'google_cse') .'/google_cse.js', 'module', 'footer');
  drupal_add_css(drupal_get_path('module', 'google_cse') .'/google_cse.css');
  // And the small differences between both.
  switch ($form_id) {
    case 'google_cse_searchbox_form':
      $form['query']['#size'] = variable_get('google_cse_searchbox_width', 15);
      $form['query']['#attributes']['title'] = t('Enter the terms you wish to search for.');
      break;
    case 'google_cse_results_searchbox_form':
      $form['query']['#size'] = variable_get('google_cse_results_searchbox_width', 40);
      $form['query']['#title'] = t('Enter your keywords');
      $form['sa']['#suffix'] = google_cse_results_gadget();
      break;
  }
  return $form;
}

/**
 * Display an Add-to-Google button.
 */
function google_cse_results_gadget() {
  if (variable_get('google_cse_results_gadget', 1) && $id = explode(':', variable_get('google_cse_cx', ''))) {
    $output = '<div id="google-cse-results-gadget">';
    $output .= '<a href="http://fusion.google.com/add?moduleurl=http%3A%2F%2Fwww.google.com%2Fcoop/api/'. $id[0] .'/cse/'. $id[1] .'/gadget">';
    $output .= '<img src="http://buttons.googlesyndication.com/fusion/add.gif" width="104" height="17" border="0" alt="Add to Google" />';
    $output .= '</a></div>';
    return $output;
  }
  else {
    return '';
  }
}

/**
 * Render the search page and custom title.
 */
function google_cse_results() {
  drupal_set_title(variable_get('google_cse_results_title', t('Search')));
  print theme('page', theme('google_cse_results'));
}

/**
 * Implementation of hook_perm().
 */
function google_cse_perm() {
  return array('search Google CSE');
}
